name: Build macOS Qt App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Qt Application for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install Qt
        run: |
          brew install qt
          echo "Qt installation path: $(brew --prefix qt)"

      - name: Set Qt Environment Variables
        run: |
          echo "export PATH=$(brew --prefix qt)/bin:$PATH" >> $GITHUB_ENV
          echo "export QTDIR=$(brew --prefix qt)" >> $GITHUB_ENV

      - name: Build Project
        run: |
          mkdir -p build
          cd build
          qmake ../V3.pro
          make -j$(sysctl -n hw.ncpu)

      - name: Create .dmg with macdeployqt
        run: |
          cd build
          macdeployqt V3.app -dmg -always-overwrite

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: V3DiskImage
          path: build/V3.dmg
