name: Build macOS Qt Project

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Qt environment (using Homebrew)
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew update

    - name: Install Qt
      run: |
        brew install qt
        echo "$(brew --prefix qt)/bin" >> $GITHUB_PATH

    # Step 3: Build the project using qmake and make
    - name: Build project
      run: |
        mkdir build
        cd build
        qmake ../V3.pro
        make
        
    # Step 4: Run macdeployqt to bundle dependencies
    - name: Run macdeployqt
      run: |
        cd bin
        macdeployqt V3.app -dmg 

    # Step 5: Upload the DMG as a GitHub Action artifact (optional)
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v3
      with:
        name: V3.dmg
        path: build/V3.dmg
